### ISSUE TITLE
docker version mismatch

### ISSUE THREAD

**Issue by umeboshi2** [objectified/vdist#1]
`APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.16, server: 1.15)")`

I got this error when trying to use vdist in a virtualenv to make a package on a debian jessie i386 system.  I have been using [another](https://github.com/umeboshi2/kermas.git) method to package a virtualenv, but the way vdist works is very appealing.

**Comment by objectified** [comment]
Hi @umeboshi2 , 

This is because the Docker daemon you appear to be running is a little older than what docker-py expects by default. vdist lets you specify Docker client arguments when instantiating the vdist Builder, but this isn't documented yet. For example, you can do this:

```
builder = Builder(docker_args={'version': '1.15'})
```

Obviously this needs to be documented, so I'm leaving this issue open until I've written this documentation. Thanks for reporting!

**Comment by objectified** [comment]
Added documentation, d48308ad9d0a4bdd3990497200708ec3ad03881b
https://github.com/objectified/vdist/blob/master/docs/howtouse.md

If you experience any further issues with this, let me know.
